### ISSUE TITLE
Add support for lsp in Doom Emacs

### ISSUE THREAD

**Issue by noponn8000** [godotengine/emacs-gdscript-mode#105]
I have installed gdscript mode in Doom Emacs, but there is no support for lsp - at least that is what the Doom documentation states.

**Comment by NathanLovato** [comment]
There's built-in support. In your init.el write the package like so `(gdscript +lsp)`. Like any language server in Doom modules, it's an option and so you need the `+lsp` flag to turn it on by default.

**Comment by NathanLovato** [comment]
![Screenshot from 2021-02-12 09-15-49](https://user-images.githubusercontent.com/12694995/107786013-ebedc800-6d12-11eb-8d9b-832c325d67a8.png)

As mentioned here in the README

**Comment by NathanLovato** [comment]
If you have issues on Doom's side, ensure you're on their `develop` git branch as it uses a rolling release system. And run the `doom upgrade` program command to upgrade to the latest version of doom.
