### ISSUE TITLE
The hydra window is very large and makes coding a bit jarring

### ISSUE THREAD

**Issue by tavurth** [godotengine/emacs-gdscript-mode#108]
The Hydra window on my machine (doom-emacs, Mac OX) is very large and takes more than half of the entire screenspace.

Is there some way to limit this size?

<img width="1552" alt="Screenshot 2021-06-09 at 20 13 46" src="https://user-images.githubusercontent.com/100964/121399556-34369300-c95f-11eb-9c3c-733b8873dbc6.png">

**Comment by NathanLovato** [comment]
Are you sure this is hydra? This looks like the language server package showing you docs interactively. And this doesn't have to do with gdscript-mode.

Hydra gives you a few keyboard shortcuts only, no docs or anything else.

**Comment by tavurth** [comment]
Oh I see, this only showed up after I installed hydra following the docs, but I guess it must be `lsp` mode. 

Is that where I should be searching?

**Comment by NathanLovato** [comment]
I would bet on lsp-ui. Try setting `lsp-ui-doc-enable` to `nil`. It's the bit that presents the docs, normally in a child frame, but depending on your emacs config or distribution it may use popup buffers like on your screenshot.

**Comment by NathanLovato** [comment]
If lsp-ui-doc is disabled, or lsp-ui is disabled, then none of the variables will affect your config as they all relate to that module.

It's most likely the `lsp` package then. gdscript-mode has no code for documentation display.

You can try lowering `lsp-signature-doc-lines`, it's set to show max `20` lines of the docs by default. If that doesn't help, can you hop on their discord? lsp devs or users could probably help you better.

Here's their website: https://emacs-lsp.github.io/lsp-mode/
