### ISSUE TITLE
Link to LSP-Docs just links back here when looking how to install

### ISSUE THREAD

**Issue by TobiasDev** [godotengine/emacs-gdscript-mode#112]
This is written inside of this README:
"For auto-completion, we rely on the lsp-mode package and the GDScript language server, which is built into Godot.

The GDScript LSP support is part of the LSP mode. To use it, you need to install lsp-mode on top of gdscript-mode and configure it. To install and configure lsp-mode, see the lsp-mode documentation."

When going to the link for the lsp-mode documentation that just links back to the Godot repo. 
![image](https://user-images.githubusercontent.com/5912371/146335848-d9e95aa9-9fc9-49f8-a3f7-09d1ac97c0ba.png)

This is the link: https://github.com/godotengine/godot

It would be nice to see one of the pages talking about how to use this, even if it is just as simple as turning the mode on. (FYI: I have not yet gotten it working on Windows, so this is how I found out).

**Comment by TobiasDev** [comment]
Sorry! Bad english. :( Yeah, they send me to the LSP website. The screenshot is from the LSP-website. They just send you back to the Godot website when you look for how to setup GDScript. https://emacs-lsp.github.io/lsp-mode/page/lsp-gdscript/

**Comment by NathanLovato** [comment]
The GDScript language server automatically runs when you run Godot. I don't think there's documentation on that. But then this is an issue for the godot-docs repository: https://github.com/godotengine/godot-docs/

Like all things with lsp mode, the setup consists mostly of running the lsp mode when the desired language server is running. For most servers they're standalone programs so your computer can launch them automatically. But in Godot's case you need to open a Godot project.

**Comment by TobiasDev** [comment]
Hmm, okay. Because I don't get it working at all in Emacs. The lsp-mode is on and gdscript-mode, but I only get auto-complete for my own variables, and nothing from Godot... I need to look into this again and see what the issue might be then (since it must be on my own side).

**Comment by NathanLovato** [comment]
This issue about the link seems solved already, so closing.
