### ISSUE TITLE
Can't open local docs with C-c C-b a

### ISSUE THREAD

**Issue by igorr0driguez** [godotengine/emacs-gdscript-mode#115]
I've downloaded a copy of the official Godot Docs, stored in folder and `setq gdscript-docs-local-path` to that folder in user-config.

However, when trying to C-c C-b a (`gdscript-docs-browse-api`) I get the following message:

"Wrong number of arguments: #<subr gdscript-docs-open>, 1".

Doing the same thing but going for the online docs (C-c C-b s) works very well.

Gdtoolkit is installed and everything else seems to be working fine (syntax highlighting, auto-completion, etc.). It's only with the offline docs I'm having trouble with.

**Comment by NaevaTheCat** [comment]
Possibly related. I get the error:

`gdscript-docs-browse-api: Wrong number of arguments: (3 . 3), 1` 

I don't know enough elisp to know if this is exactly the same.

The error occurs evaling

`(gdscript-docs-open "/path/constructed/by/gdscript-docs-browse-api")`

Where gdscript-docs-browse-api has the same call [here](https://github.com/godotengine/emacs-gdscript-mode/blob/d9e1f7f766c73115de8ce2815bc249069636c3db/gdscript-docs.el#L51)

Opening it directly with eww-open-file does the expected, so it seems like the function is called wrong? 

Like I said I don't know elisp.

on emacs 28.1, archlinux  5.18.6-arch1-1

**Comment by benjamin-asdf** [comment]
Issue is in gdscript-docs.el


fix: 

-(defun gdscript-docs-open (url &args _)
+(defun gdscript-docs-open (url &rest _)


`&args` is not elisp. It thinks `url &args _` is 3 params
