### ISSUE TITLE
"open-project-in-editor" Flatpak Support

### ISSUE THREAD

**Issue by reisaraujo-miguel** [godotengine/emacs-gdscript-mode#119]
I don't know if this is possible, due to the sand-boxed nature of flatpaks, but I would like to be able to use the `M-x gdscript-godot-open-project-in-editor` to launch the flatpak version of Godot Engine.

I tried a workaround by creating a shell script that launches the flatpak and setting `(setq gdscript-godot-executable "path/to/godot")` to the script, but it does not works right. When I try opening or running the project through emacs, it just opens the Project Manager

This is the shell script, it just launches the Godot engine flatpak
```sh
#!/usr/bin/env bash

flatpak run org.godotengine.Godot
```

**Comment by reisaraujo-miguel** [comment]
Update

I was able to make my workaround work by adding 3 "argument variables" (don't if that's really how they're called) at the end of the run command:
```sh
#!/usr/bin/env bash

flatpak run org.godotengine.Godot $1 $2 $3
```

But it would still be cool to have this without needing an workaraound

**Comment by reisaraujo-miguel** [comment]
When I try running `M-x gdscript-godot-open-project-in-editor` I get the error: `start-process: Searching for program: No such file or directory, flatpak run org.godotengine.Godot`

**Comment by reisaraujo-miguel** [comment]
> Hello,@reisaraujo-miguel . Since I can't start the flatpak version of godot properly, can you try adding the following code in `init.el` and test it to work?
> 
> ```
> 
>   (with-eval-after-load 'gdscript-mode
>     (defun gdscript-comint--run (arguments)
>       "Run godot in comint mode.
> 
>   ARGUMENTS are command line arguments for godot executable.
>   When run it will kill existing process if one exists."
>       (let ((buffer-name (gdscript-util--get-godot-buffer-name (member "-e" arguments)))
>             (inhibit-read-only t))
>         (if (not (or (file-executable-p gdscript-godot-executable)
>                      (executable-find gdscript-godot-executable)
>                      (string-match-p (rx "org.godotengine.Godot") gdscript-godot-executable)))
>             (error "Error: Could not execute '%s'.  Please customize the `gdscript-godot-executable variable'" gdscript-godot-executable)
>           (with-current-buffer (get-buffer-create buffer-name)
>             (when gdscript-gdformat-save-and-format
>               (gdscript-comint-gdformat--modified-buffers))
>             (unless (derived-mode-p 'godot-mode)
>               (godot-mode)
>               (buffer-disable-undo))
>             (erase-buffer)
>             (comint-exec (current-buffer) buffer-name gdscript-godot-executable nil arguments)
>             (set-process-sentinel (get-buffer-process (current-buffer)) 'gdscript-comint--sentinel)
>             (pop-to-buffer (current-buffer))))))
>     (setq gdscript-godot-executable "flatpak run org.godotengine.Godot"))
> ```

When I try running `M-x gdscript-godot-open-project-in-editor` I get the error: `start-process: Searching for program: No such file or directory, flatpak run org.godotengine.Godot`

**Comment by xiliuya** [comment]
According to your feedback, I have modified the following code.
Is it available after being added to `init.el`?
```emacs-lisp
(with-eval-after-load 'gdscript-mode
  (defun gdscript-comint--run (arguments)
    "Run godot in comint mode.

  ARGUMENTS are command line arguments for godot executable.
  When run it will kill existing process if one exists."
    (let ((buffer-name (gdscript-util--get-godot-buffer-name (member "-e" arguments)))
          (inhibit-read-only t)
          (command gdscript-godot-executable))
      ;; support flatpak
      (if (string-match-p (rx "run org.godotengine.Godot") command)
          (let ((exec-split (split-string command)))
            (setq command (car exec-split))
            (setq arguments (append (cdr exec-split) arguments ))))

      (if (not (or (file-executable-p command)
                   (executable-find command)
                   (string-match-p (rx "org.godotengine.Godot") command)))
          (error "Error: Could not execute '%s'.  Please customize the `command variable'" command)
        (with-current-buffer (get-buffer-create buffer-name)
          (when gdscript-gdformat-save-and-format
            (gdscript-comint-gdformat--modified-buffers))
          (unless (derived-mode-p 'godot-mode)
            (godot-mode)
            (buffer-disable-undo))
          (erase-buffer)
          (comint-exec (current-buffer) buffer-name command nil arguments)
          (set-process-sentinel (get-buffer-process (current-buffer)) 'gdscript-comint--sentinel)
          (pop-to-buffer (current-buffer))))))
  (setq gdscript-godot-executable "flatpak run org.godotengine.Godot"))
```

**Comment by reisaraujo-miguel** [comment]
Yes. It did work now

**Comment by xiliuya** [comment]
`flatpak command` will be supported in #127  merge.
