### ISSUE TITLE
add support for eglot ？

### ISSUE THREAD

**Issue by xiliuya** [godotengine/emacs-gdscript-mode#121]
The relevant discussion is in: [bug#62795](https://lists.gnu.org/archive/html/bug-gnu-emacs/2023-04/msg01070.html)

To accommodate eglot, can we add functions to the package?

```emacs-lisp
(defun gdscript-mode-find-lsp (interactive-p)
  (let (port)
    ;; search for the port in this order: $XDG_CONFIG_HOME, /etc,
/ /usr.
    ;; This uses some regexp extracted from your awk expression.
    (ignore port 'todo)
    ;; then return the host-port list when found
    (and port (list "localhost" port))))
```

**Comment by RuijieYu** [comment]
Note that João proposed an alternate name in a different subthread: `gdscript-eglot-contact`.
