### ISSUE TITLE
This repository needs a new maintainer

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/emacs-gdscript-mode#123]
I've initially worked on this package in the hope that it would be useful to fellow Emacs users.

I since stopped using Emacs, and I don't have the time to maintain this package. As a result, this repository needs a new maintainer, someone who is actively using Emacs, who's at least a little familiar with lisp, and who's willing to review, test, and merge contributions to this package.

**Comment by xiliuya** [comment]
Hello,  @NathanLovato .
I want to become the maintainer of this repository. 
My situation:
- I haven't had experience maintaining such a project yet. 
- Nor have any `emacs` packages been published on `MELPA`.
- Little familiar with lisp.
- I willing to review, test, and merge contributions to this package.

I will try my best to do well. Feel free to give your comments. 

-------
 + xiliuya 
 + Thu Apr 20 2023

**Comment by NathanLovato** [comment]
Thank you very much for offering your help. As this repository is part of the Godot organization, I've asked in the development chat if there were particular rules I had to observe to give you the power to merge pull requests.

Please ensure that you understand these responsibilities of a maintainer on a somewhat niche repository like this:

- You will not only have to review but also test the code in pull requests, and that the Emacs package works as intended when merging pull requests.
- You make decisions regarding which features/code to include and which not to include, listening to users. 
- You need to respect [Godot's code of conduct](https://godotengine.org/code-of-conduct/) at all times.
- You're also the person who will read, answer, and triage issues.

On top of that, you can add features yourself directly.

Note that this project is pretty low bandwidth, it's not like you'll be overwhelmed with messages and requests. Typically with a plugin like this, once it's updated for the latest version of Godot and Emacs, it just works and you only get occasional bug reports, bug fix PRs, and requests.

Until I get a reply from Godot's team, you can already start doing code reviews, test pull requests, comment on their code, and tell me in a pull request when it's ready to merge. I'll gladly merge for you.

That'll be a great way for you to try the role of maintainer too and ensure you're fine with it if you've never done it before.

**Comment by xiliuya** [comment]
>     * You will not only have to review but also test the code in pull requests, and that the Emacs package works as intended when merging pull requests.
> 
>     * You make decisions regarding which features/code to include and which not to include, listening to users.
> 
>     * You need to respect [Godot's code of conduct](https://godotengine.org/code-of-conduct/) at all times.
> 
>     * You're also the person who will read, answer, and triage issues.

I will do my best to do it.
I have read and understood the Godot Code of Conduct.
Accept community supervision and be responsible for your words and actions.

> Until I get a reply from Godot's team, you can already start doing code reviews, test pull requests, comment on their code, and tell me in a pull request when it's ready to merge. I'll gladly merge for you.
> 
> That'll be a great way for you to try the role of maintainer too and ensure you're fine with it if you've never done it before.

Thanks for the information .
I will start testing and commenting around 19:00 UTC+8.

**Comment by NathanLovato** [comment]
@xiliuya thank you for your reply and the work you've already been doing. I just invited you as a collaborator to the repository. It'll give you the ability to manage issues and pull requests, though it won't immediately allow you to push code to the repository.

I'm trying to see if there's a way to give you extra permissions, such as merging pull requests.

I'm closing this issue as you're now the candidate for the maintainer role. I'll be overseeing your contributions during a transition period and if all goes well, you'll be granted more access.

There aren't precise guidelines for side repositories like this one at Godot, so I currently don't have additional information, unfortunately, but we just want to ensure that the project has a great maintainer. You're off to a good start, I really appreciate the good communication in issues and pull requests.

**Comment by NathanLovato** [comment]
@xiliuya a quick update, we promoted your permissions, allowing you to merge pull requests that got at least one approved review.  You should be able to use the review feature on pull requests to approve them and then merge them (except if you make your own pull requests, I believe, then someone else will need to review and merge).

**Comment by jcs090218** [comment]
@NathanLovato First of all, thanks for creating this package! 🚀

I would like to become a maintainer as well. Is there still space for another maintainer? :) Here is my situation:

1. I've maintain few elisp packages, [popup-el](https://github.com/auto-complete/popup-el), [cask](https://github.com/cask/cask), etc.
2. 40+ packages published on MELPA, [lsp-grammarly](https://github.com/emacs-grammarly/lsp-grammarly), [sideline](https://github.com/emacs-sideline/sideline), etc.
3. Familiar with elisp, yes (above average)
4. Willing to answer questions, review PR,s etc.

Read and understood the [Godot Code of Conduct](). 👍

**Comment by xiliuya** [comment]
Hello, @NathanLovato , 
> You should be able to use the review feature on pull requests to approve them and then merge them (except if you make your own pull requests, I believe, then someone else will need to review and merge).
When I approve these changes, The following situation is displayed:
![2023-04-22-104412](https://user-images.githubusercontent.com/67564860/233757974-217a2bb1-6836-4490-8c52-30ce74f44f63.png)

Is it because of my operation error?

**Comment by NathanLovato** [comment]
@jcs090218 I'll ask the Godot team. It's nice if you two can share the workload. The only thing I'd add is you'll have to make sure to agree on the direction the project should take, which features to include and which not to include.

@xiliuya I've looked at the repository settings, unfortunately I don't see one that'd allow you to merge but your own PRs specifically for now. I've asked a more experienced Godot maintainer for insights on this.

**Comment by xiliuya** [comment]
@NathanLovato  I see, I can  review the code, and then other maintainers do a merge commit, which is fine.

**Comment by NathanLovato** [comment]
@xiliuya could you please check another pull request? Godot's project administrator Akien changed some settings to hopefully allow you to merge.

**Comment by NathanLovato** [comment]
@jcs090218 You now should have the same access as @xiliuya. I've seen you around a couple of repositories, you seem active and experienced, and we're happy to have two persons to share the load of maintenance here.

The only thing the two of you should strive for on top of respecting the code of conduct and all is reaching good levels of consensus if the need arises. That is, if users disagree on features they want in the package, or if someone insists to have a very niche feature, you'll have to come to an agreement as to how to handle these things.

Note that it should be exceptional for a package like this one, but it's just something I have to mention now you're two persons with the ability to review and merge pull requests.

Being two also means that you can both contribute and review and merge each other's pull requests (you won't be able to merge your own or push directly to the main branch for now due to Godot being a very large project, they have some protection rules in place).

**Comment by xiliuya** [comment]
@NathanLovato I think I have the authority now.
![2023-04-22-230724](https://user-images.githubusercontent.com/67564860/233792420-b017d5b9-d3c7-4a88-b573-c5b1f10db1c5.png)
