### ISSUE TITLE
gdscript-eglot-version should be documented in README

### ISSUE THREAD

**Issue by MenacingMecha** [godotengine/emacs-gdscript-mode#129]
With the changes made in 30c4d48f81d5e52e8667cc10780e4af743e27f96, eglot now longer works out of the box for Godot 3, and requires `gdscript-eglot-version` to be customized to `3`.

As Godot 3 is still used in production, this should be documented in the README.

**Comment by adamscott** [comment]
I encourage you to create a PR for the correction in the README, if you have time!

**Comment by MenacingMecha** [comment]
I can give it a go; only have a very high level understanding of how eglot works, but should be enough for a quick example configuration.
