### ISSUE TITLE
eglot + godot3.5.2: Searching for program: No such file or directory, localhost:6008

### ISSUE THREAD

**Issue by habamax** [godotengine/emacs-gdscript-mode#132]
Hi,

I might be missing something obvious, but couldn't figure it out from both `eglot` and `gdscript-mode` docs.

Looks like I can't connect to godot 3.5.2 language server using Eglot (emacs 28.2 on fedora 38):

![image](https://github.com/godotengine/emacs-gdscript-mode/assets/234774/0a189938-426c-43f1-ae97-0a041ad2a429)

Both eglot and gdscript-mode are of the latest versions:

```
(use-package eglot)

(use-package gdscript-mode
  :custom
  (gdscript-eglot-version 3))
```

Port is default:
![image](https://github.com/godotengine/emacs-gdscript-mode/assets/234774/fd76f8aa-d808-4555-9de3-20595c07af84)

[![asciicast](https://asciinema.org/a/vcSL8XNBOLHrgbu97bKsJCiRj.svg)](https://asciinema.org/a/vcSL8XNBOLHrgbu97bKsJCiRj)

PS, `127.0.0.1:6008` doesn't work too
![image](https://github.com/godotengine/emacs-gdscript-mode/assets/234774/50b17056-3be6-4c0a-b0be-0dd5785a2c62)

Eglot version:
```
;; Version: 1.15
;; Author: João Távora <joaotavora@gmail.com>
;; Maintainer: João Távora <joaotavora@gmail.com>
;; URL: https://github.com/joaotavora/eglot
;; Keywords: convenience, languages
;; Package-Requires: ((emacs "26.3") (jsonrpc "1.0.16") (flymake "1.2.1") (project "0.9.8") (xref "1.6.2") (eldoc "1.14.0") (seq "2.23") (external-completion "0.1"))
```

**Comment by habamax** [comment]
I was thinking the issue might be with godot server, but vim with `coc.nvim` works:

![image](https://github.com/godotengine/emacs-gdscript-mode/assets/234774/709c3603-2fe8-483b-92c8-9454c0a9d95b)

Relevant settings in `:CocConfig`:

```
{
    "languageserver": {
        "godot": {
            "host": "127.0.0.1",
            "filetypes": ["gdscript"],
            "port": 6008
        }
    }
}
```

Same host and port...

**Comment by MenacingMecha** [comment]
Is `godot` in your path? If not, you might have to customize `gdscript-godot-executable` to point to the engine.

I'm also running emacs 28 with Godot 3.52 on Fedora 38, where there was a period (I'm only now aware that's over) that only Godot 4 was available in system repositories. As `gdscript-godot-executable` didn't exist yet, I had to do the workaround of having a script in path named `godot` pointing to a downloaded executable.

**Comment by habamax** [comment]
It is in the path, I can run scene or a project.

**Comment by habamax** [comment]
I am able to connect after a laptop restart `¯\_(ツ)_/¯`

Closing.
