### ISSUE TITLE
Eglot post-command-hook error for Godot3 flatpak

### ISSUE THREAD

**Issue by MenacingMecha** [godotengine/emacs-gdscript-mode#134]
Error message:
```
Reverted buffer
Use M-x make-directory RET RET to create the directory and its parents
Error in post-command-hook (#[0 "\300\303!\205\0r\211q\210\304\305\301\242\306#\210
?\205\0\307\310\311 \")\207" [#<buffer redacted_script_name.gd> (#0) eglot--managed-mode buffer-live-p remove-hook post-command-hook t apply eglot--connect eglot--guess-contact] 5]): (wrong-type-argument processp nil)
```

Relevant section of `init.el`:
``` elisp
(use-package eglot)

(use-package gdscript-mode
  :custom (gdscript-eglot-version 3))
```

`godot` in `PATH` is the following:
``` sh
#!/usr/bin/env sh
flatpak run org.godotengine.Godot3 $@
```

As a workaround, I can use the self-contained binary for Godot 3 can be used instead. (I'm also getting editor performance issues with the Godot 3 flatpak, so it not working with eglot is not a big deal for me.)

**Comment by xiliuya** [comment]
Hello, @MenacingMecha :
I think this is because flatpak does not create `~/.config/godot/editor_settings-3.tres` .
Try it if you need to use it:
```sh
ln -s ~/.var/app/org.godotengine.Godot/config/godot/ ~/.config/godot/
```
This may help you resolve the above errors.

**Comment by MenacingMecha** [comment]
`~/.config/godot/editor_settings-3.tres` being present fixed things, cheers!
