### ISSUE TITLE
Symbol’s value as variable is void: gdscript-hydra--menu

### ISSUE THREAD

**Issue by iamtoaster** [godotengine/emacs-gdscript-mode#135]
After installation of this mode with lsp-mode and hydra.el, whenever I try to open a gdscript hydra in a gdscript file with `C-c r` I get the message seen in the title:
```
gdscript-hydra-show: Symbol’s value as variable is void: gdscript-hydra--menu
```
And the hydra does not show up.

**Comment by jcs090218** [comment]
Interesting, we didn't require hydra to be installed automatically. See 

https://github.com/godotengine/emacs-gdscript-mode/blob/3e2ae19f036fedc4cc1c1382cd6bb4f12b1aeb76/gdscript-hydra.el#L8

The error should go away after installing the hydra.el manually. 🤔

**Comment by jcs090218** [comment]
Ah, sorry. I was confused by the upstream hydra.el. It should be the issue missing the variable in the package `gdscript-hydra.el`. Where is the variable `gdscript-hydra--menu` defined? 🤔 I'm gonna ping someone else in the group since the code was 2 years old.

cc @NathanLovato @xiliuya

**Comment by NathanLovato** [comment]
It's in the function `gdscript-hydra--create` it seems. I don't remember the API, this was a contribution I just reviewed and tested at the time. What I can say is that it used to work, and what I'd check based on this issue is whether there was a compatibility breakage/an API change on the hydra package's side with package updates over the years.

**Comment by xiliuya** [comment]
@jcs090218 `gdscript-hydra--menu` defined in `gdscript-hydra.el` line: 118 :
```
 (defhydra gdscript-hydra--menu (:hint none
                                        :body-pre (setq gdscript-hydra--open t)
                                        :before-exit (setq gdscript-hydra--open nil))
...)

```

defhydra is an autoloaded Lisp macro in ‘hydra.el’.

**Comment by xiliuya** [comment]
Hello ,@iamtoaster :

`gdscript-hydra` does not require the installation of `lsp-mode`. 

From the above information, that gdscript-hydra.el may not have been automatically loaded. 
You can try to eval `(require 'gdscript-hydra)`

Under the default configuration, Hydra is runs well on emacs-29.

**Comment by iamtoaster** [comment]
Evald it, no effect. Still the same message. Maybe I installed the mode wrong? It is installed like so:
```
(use-package gdscript-mode
    :straight (gdscript-mode
               :type git
               :host github
               :repo "godotengine/emacs-gdscript-mode"))

(add-hook 'gdscript-mode-hook #'lsp)
```
Hydra.el is installed using simply `(use-package hydra)`

**Comment by iamtoaster** [comment]
I fixed the issue, it seems it was due to my migration from package.el to straight.el. I deleted all the folders that contained packages in my .emacs.d and let straight.el reinstall everything from scratch. The hydra now works as expected.
