### ISSUE TITLE
Are we suppose to put localhost:6005 in our config (macOS)?

### ISSUE THREAD

**Issue by whompyjaw** [godotengine/emacs-gdscript-mode#144]
Maybe I am overlooking something here, but running `eglot` doesn't "just work". I have to manually call `eglot` then provide `localhost:6005` which I would not have known if I hadn't found this issue: https://github.com/godotengine/emacs-gdscript-mode/issues/137

On macOS
```elisp
(use-package gdscript-mode
  :straight (gdscript-mode
             :type git
             :host github
             :repo "godotengine/emacs-gdscript-mode")
  :hook (gdscript-mode . eglot-ensure))
```
Am I suppose to open a project a specific way?

When I open a `sctipt.gd` in a project I get
`﻿[eglot] (warning) Wrong type argument: processp, nil`

So then I have to manually run `M-x eglot` and type in `localhost:6005` it loads eglot

**Comment by whompyjaw** [comment]
Gleaned from this comment:
https://github.com/godotengine/emacs-gdscript-mode/issues/137#issuecomment-1729646156, I copied the `~/Library/Application Support/Godot/editor_settings-4.tres` to ~/.config/godot` and eglot starts up as expected when opening a `*.gd` script. So I guess or assume that in your `init.el` maybe `gdscript-godot-config-directory` in which case you would use the Apple path, or you copy/symlink the `*.tres` file to ~/.config/godot` 

Can any other macOS users verify this works, and if so, can I make a PR to add this requirement for macOS?

**Comment by jcs090218** [comment]
I'm not sure about `eglot,` but in `lsp-mode,` you need to open the project that started the language server.
