### ISSUE TITLE
Integrate gdlint with flycheck

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/emacs-gdscript-mode#25]
There's a community developped parser and linter for gdscript called gdlint. It comes with gdformat that we already support in this package.

https://github.com/scony/godot-gdscript-toolkit/

Call `gdlint file.gd` and you'll get an output like:

```
file.gd:line_number: Error: Error message (linter-error-id)
```

We could integrate this with flycheck. The linter doesn't have all the tests available in Godot itself right now, but it's easy to extend.

**Comment by NathanLovato** [comment]
@ofrank123 when you work on this, I recommend to not install the version available on pip, but to clone the project, checkout to the `feature/gdtoolkit_speedup` branch, and install this one. You can do so like this:

1. Navigate to the repo in your shell
2. `pip3 install .`

That version uses disk cache, spawning the process and running the linter much faster than the current stable.

**Comment by ofrank123** [comment]
sounds good, I'll get to work on this sometime in the next couple days.

**Comment by NathanLovato** [comment]
We have linting support through lsp, closing for now
