### ISSUE TITLE
Put a lower Emacs version requisite

### ISSUE THREAD

**Issue by zhensydow** [godotengine/emacs-gdscript-mode#71]
**I'm submitting a...**

- [ ] Bug report.
- [X] Feature request.

## Feature request ##

Currently in my actual Linux distribution I can install this package because the emacs version required is greater that the installed one. 

It should be possible to lower the Emacs version required without to much ado. E.g: Emacs versions of common Linux Distributions:
- Ubuntu 18.04 LTS  == 25.2
- Linux Mint 19.3 == 25.2
- Debian Stable == 26.1
- Centos 8 == 26.1

Thanks,

**Comment by NathanLovato** [comment]
I have a big workload and don't want to have to support older versions of Emacs for what I expect is a small amount of potential users.

**Comment by NathanLovato** [comment]
Is this issue still relevant? With ubuntu LTS 20.04 and Emacs 27.1 out, hopefully fewer persons are stuck with Emacs 25 now.

Another thing I forgot to mention: I really wouldn't recommend doing GDScript in Emacs without Emacs 27, as it we use the language server for auto-completion, and with lisp-based JSON parsing, performance is really bad in Emacs 26.x.

**Comment by zhensydow** [comment]
Yes, new LTS makes this ticket less urgent, or maybe unnecessary. I think it could be close.

**Comment by NathanLovato** [comment]
Thanks

**Comment by muhuk** [comment]
Debian stable still has 26.1 :disappointed:

**Comment by Calinou** [comment]
@muhuk Look into using a [Flatpak](https://www.flathub.org/apps/details/org.gnu.emacs), a third-party repository or compiling Emacs from source
