### ISSUE TITLE
Running project or scene throws error

### ISSUE THREAD

**Issue by dirodriguezm** [godotengine/emacs-gdscript-mode#73]
Hi ! I'm new to Godot so any help with this problem will be appreciated. It probably isn't really a bug but some problem with my setup.

**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
When trying to execute `gdscript-godot-run-project` I get the following error:

```
Godot Engine v3.2.stable.custom_build - https://godotengine.org
ERROR: initialize: X11 Display is not available
   At: platform/x11/os_x11.cpp:132.
```

But if I run it from Godot Engine then it runs without problems.

**What is the expected behavior?**
The scene or project runs without errors.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

1. Load spacemacs
2. pyenv-workon `<my godot env>`
3. Open a .gd file from a project (currently following [this tutorial from gdquest](https://www.gdquest.com/tutorial/godot/2d/your-first-game/))
4. `C-c C-r r`

## Other ##

**Other information** 

- I'm using spacemacs 0.300.0@26.3
- Godot version 3.2 installed using `apt install godot3`
- Installed this package following the spacemacs instructions
- Installed gdtoolkit on virtualenv
- I had set `gdscript-godot-executable` to `godot3` wich is the executable that I'm using

**Comment by NathanLovato** [comment]
> pyenv-workon <my godot env>

What is that line for? Are you creating a python environment and a subshell for your Godot project?

The error says your display isn't available. It's not related to the emacs gdscript mode. I'd bet on the use of an environment

**Comment by dirodriguezm** [comment]
Thanks for the reply. I tried running it without a virtual environment and the error is the same. How does gdscript-mode interact with the display ? There might be something that I'm missing.

**Comment by NathanLovato** [comment]
These commands call godot via the shell, generating a command like `godot path/to/your/project.godot`. It seems there's an issue with the command being ran from the emacs shell. Which shell are you using? Here, with eshell as my default shell, I haven't had issues.

**Comment by NathanLovato** [comment]
As there isn't much info I'm closing for now. It doesn't look like a bug in Emacs. Let me know if you have more information and we can reopen the issue.
