### ISSUE TITLE
<info required> identifying scripts to run 

### ISSUE THREAD

**Issue by rileyrg** [godotengine/emacs-gdscript-mode#91]
In gdscript-project when we want to locate scripts the following code is used :

```
(defun gdscript-project--get-all-scripts ()
  "Find all script files and let user choose one.
Since detection of script files require inspection of file contents,
this use ag for performance."
  (if (not (featurep 'ag))
      (error (format "Buffer %s is no script file. To see all available scripts in current project install package 'ag'." (buffer-name)))
    (ag-project-regexp "^extends SceneTree|^extends MainLoop")
    (setq gdscript-project--script-list nil)
    (add-hook 'ag-search-finished-hook #'gdscript-project--ag-find-next-script)))

```

My Question is : is this grepping really necessary and is it still applicable? As a beginner to to GDScript, I have some scripts  (.gd extension) that do not have any obvious relation to these "^extends" lines.

When I select run script from the hydra it doesn't show me any scripts. Is this broken?

I have some code to select from .gd files (and potentially .... others too, like .cs,  I guess when I know more about it) in the project hierarchy (which also does a small restructure to slightly better re-use project root file recognition)) and am happy to do a pull request for that if deemed helpful.

**Comment by NathanLovato** [comment]
That's expected. Maybe the documentation could be clearer.

This function is only used to find and run standalone scripts, and you can't run a standalone GDScript file via the command line `godot` executable unless it extends MainLoop or SceneTree, hence the regex.

I personally don't use that feature and don't know what are its practical applications, but at least it's working as intended.

A feature to open .gd files only in the project would be separate. With projectile and helm or ivy though, I personally don't find much of a need for it, as writing `gd$` filters a project file search down to gdscript files already.

**Comment by rileyrg** [comment]
Thanks for the clarification.
