### ISSUE TITLE
Default keybindings could be provided as a keymap

### ISSUE THREAD

**Issue by aarvay** [godotengine/emacs-gdscript-mode#93]
The default keybindings that this mode assumes conflicts with what I've already setup. I suggest, that the default keybindings should be provided as keymap that the user can then bind it to a key. Also binding imenu should just be a suggestion, alike me, many would've already bound it to something else (in my case `C-c i` which this package rebinds to insert-file-path-at-point). its just too confusing.

**Comment by aarvay** [comment]
For inspiration, taken from `projectile.el`

```el
(defvar projectile-command-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "a") #'projectile-find-other-file)
    (define-key map (kbd "b") #'projectile-switch-to-buffer)
    (define-key map (kbd "C") #'projectile-configure-project)
    (define-key map (kbd "c") #'projectile-compile-project)
    (define-key map (kbd "d") #'projectile-find-dir)
    ; ...
    ; ...
    ; ...
    ; .....
    map)
  "Keymap for Projectile commands after `projectile-keymap-prefix'.")
(fset 'projectile-command-map projectile-command-map)
```

In my config I then, 

```el
(use-package projectile
  :bind-keymap ("C-c p" . projectile-command-map))
```

Now all the projectile commands neatly come under `C-c p` and I can access them like `C-c p a` for `projectile-find-other-file` etc.

Same way, I should be able to bind all gdscript mode specific stuff under `C-c g` for ex and be able to do `C-c g i` instead of `C-c  i` for `gdscript-completion-insert-file-path-at-point`.

**Comment by cmirdesouza** [comment]
Reading the code of [gdscript-mode.el - Line 53](https://github.com/godotengine/emacs-gdscript-mode/blob/d392e8aa7e7c6dd79ce52fb55d78f7acfa443194/gdscript-mode.el#L53) seems to be implemented.
The issue can be closed.

**Comment by Calinou** [comment]
Closing per @cmirdesouza's comment.
