### ISSUE TITLE
When I press enter on the completion it deletes it

### ISSUE THREAD

**Issue by Valeriooooh** [godotengine/emacs-gdscript-mode#99]
Hi I had this problem for some time and I can't seem to figure it out.
Every time I am writing something and it shows me the completions, I press enter on one of them and it just deletes the keyword I was writing and it returns an error.

Image showing the error:
[https://imgur.com/a/ZEiClVP](url)

**Comment by NathanLovato** [comment]
I don't think it's an issue with this package, but rather with the language server. Either it's the language server in the Godot engine that's not fully compatible with the lsp package or something in the lsp package for Emacs.

Could you list the precise steps you follow to reproduce the problem? Does it always happen if you follow the steps? What does the *lsp-log* buffer contains? Press `M-x list-buffers` to access the list of open buffers.

**Comment by Valeriooooh** [comment]
Strangely it started working properly after 2 months.
I'm sorry to bother.
Cheers
